# Data Cleaning

In [396]:
import pandas as pd
import numpy as np

In [397]:
df=pd.read_excel("raw.xlsx")

In [398]:
df.head()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Payment_Method,Remittance_Amount,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date
0,SHP-100001,created,FORWARD,2026/07/12,4590,SEV-000001,1,NaN,0,trk-9001,...,Prepaid,NaN,NaN,NaN,NaN,₹527.20,₹40.00,NaN,INR,12 July 2026
1,SHP-100001,Picked Up,Forward,12 July 2026,4590,SEV-000002,1,NaN,No,trk-9001,...,Prepaid Online,NaN,NaN,NaN,NaN,527.2,40.00,NaN,INR,2026-07-12
2,SHP-100001,In Transit,Forward,2026/07/12,4590,SEV-000003,1,NaN,0,trk-9001,...,Prepaid Online,NaN,NaN,NaN,NaN,527.2,40.00 INR,NaN,INR,13 July 2026
3,SHP-100001,out_for_delivery,Forward,2026-07-12,4590,SEV-000004,1,NaN,FALSE,trk-9001,...,PREPAID,NaN,NaN,NaN,NaN,527.2,40.00,NaN,₹,16-Jul-2026
4,SHP-100001,Delivered,Forward,2026-07-12,4590,SEV-000005,1,NaN,N,trk-9001,...,PREPAID,NaN,NaN,NaN,NaN,527.20 INR,Rs. 40.00,NaN,inr,2026/07/16

In [399]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Payment_Method,Remittance_Amount,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date
495,SHP-100018,In Transit,Forward,11 August 2026,4620,SEV-000496,1,NaN,no,trk-9016,...,COD,NaN,NaN,NaN,NaN,843.28 INR,NaN,NaN,INR,12 August 2026
496,SHP-100019,In Transit,Forward,2026-09-19,37584,SEV-000497,1,NaN,0,TRK-9017,...,COD,NaN,NaN,NaN,NaN,190.58 INR,25.00,NaN,INR,2026-09-20
497,SHP-100020,In Transit,Forward,04-Jul-2026,11368,SEV-000498,1,NaN,FALSE,trk-9018,...,Cash on Delivery,NaN,NaN,NaN,NaN,779.32,Rs. 25.00,NaN,INR,2026-07-05
498,SHP-100021,In Transit,Forward,2026-07-27,22950,SEV-000499,1,NaN,N,TRK-9019,...,prepaid,NaN,NaN,NaN,NaN,644.66,₹0.00,NaN,INR,2026/07/28
499,SHP-100022,In Transit,Forward,2026-07-05,32760,SEV-000500,1,NaN,N,trk-9020,...,PREPAID,NaN,NaN,NaN,NaN,585.53 INR,NaN,NaN,INR,2026-07-06

# 1. Trim and normalize shipment, parcel, route, stop, and tracking IDs; map carrier aliases to canonical identifiers.

Clean the ID columns

In [400]:
columns = [
    'Shipment_ID',
    'Parcel_ID',
    'Route_ID',
    'Stop_ID',
    'Tracking_ID',
    'Carrier_ID'
]

for col in columns:
    df[col] = df[col].str.strip().str.upper()

Clean carrier names and aliases

In [401]:
df['Carrier_Name'] = df['Carrier_Name'].str.strip().str.upper()

df['Carrier_Alias'] = df['Carrier_Alias'].str.strip().str.upper()

Replace carrier aliases with standard names

In [402]:
df['Carrier_Alias'] = df['Carrier_Alias'].replace({
    'FAST SHIP': 'FASTSHIP',
    'FAST-SHIP': 'FASTSHIP',
    'ROAD X': 'ROADX',
    'ROAD-X': 'ROADX',
    'SWIFT POST': 'SWIFTPOST',
    'SWIFT-POST': 'SWIFTPOST'
})

# 2. Parse event timestamps and normalize timezone offsets to UTC while retaining source timezone when useful.

 Convert timestamp to datetime in UTC

In [403]:
df['Event_Timestamp'] = pd.to_datetime(df['Event_Timestamp'], utc=True,errors='coerce')

-> it is use to find the unique value

In [404]:
df['Event_Timestamp'].unique()

<DatetimeArray>
['2026-07-12 02:02:00+00:00', '2026-07-12 03:30:00+00:00',
 '2026-07-12 21:15:00+00:00',                       'NaT',
 '2026-07-11 01:39:00+00:00', '2026-07-03 02:42:00+00:00',
 '2026-07-03 04:36:00+00:00', '2026-07-05 01:57:00+00:00',
 '2026-08-13 00:53:00+00:00', '2026-07-13 23:30:00+00:00',
 ...
 '2026-08-01 10:06:00+00:00', '2026-08-29 03:21:00+00:00',
 '2026-08-29 03:57:00+00:00', '2026-08-30 01:02:00+00:00',
 '2026-08-17 02:56:00+00:00', '2026-08-17 19:40:00+00:00',
 '2026-08-20 02:42:00+00:00', '2026-08-20 12:12:00+00:00',
 '2026-07-17 01:13:00+00:00', '2026-09-04 04:30:00+00:00']
Length: 193, dtype: datetime64[ns, UTC]

In [405]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 154 entries, Shipment_ID to Reporting_Date
dtypes: datetime64[ns, UTC](1), float64(35), int64(8), object(110)
memory usage: 601.7+ KB

# 3. Standardize carrier, service level, warehouse, depot, and delivery-zone names using reference tables.

In [406]:
df['Carrier_Name'] = df['Carrier_Name'].str.strip().str.upper()
df['Service_Level'] = df['Service_Level'].str.strip().str.upper()
df['Warehouse_Name'] = df['Warehouse_Name'].str.strip().str.upper()
df['Depot_Name'] = df['Depot_Name'].str.strip().str.upper()
df['Delivery_Zone'] = df['Delivery_Zone'].str.strip().str.upper()

Replace different names with standard names

In [407]:
df['Carrier_Name'] = df['Carrier_Name'].replace({
    'FAST SHIP': 'FASTSHIP',
    'FAST-SHIP': 'FASTSHIP'})

df['Service_Level'] = df['Service_Level'].replace({
    'SAME DAY': 'SAME-DAY',
    'NEXT DAY': 'NEXT-DAY'
})

In [408]:
df['Carrier_Name'].unique()

array(['FASTSHIP', 'ROADX', 'SWIFTPOST', 'ROAD X', 'ROAD-X', 'GREENLINE',
       'GREEN-LINE', 'SWIFT POST', 'GREEN LINE', 'SWIFT-POST'],
      dtype=object)

In [409]:
df.head()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Payment_Method,Remittance_Amount,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date
0,SHP-100001,created,FORWARD,2026/07/12,4590,SEV-000001,1,NaN,0,TRK-9001,...,Prepaid,NaN,NaN,NaN,NaN,₹527.20,₹40.00,NaN,INR,12 July 2026
1,SHP-100001,Picked Up,Forward,12 July 2026,4590,SEV-000002,1,NaN,No,TRK-9001,...,Prepaid Online,NaN,NaN,NaN,NaN,527.2,40.00,NaN,INR,2026-07-12
2,SHP-100001,In Transit,Forward,2026/07/12,4590,SEV-000003,1,NaN,0,TRK-9001,...,Prepaid Online,NaN,NaN,NaN,NaN,527.2,40.00 INR,NaN,INR,13 July 2026
3,SHP-100001,out_for_delivery,Forward,2026-07-12,4590,SEV-000004,1,NaN,FALSE,TRK-9001,...,PREPAID,NaN,NaN,NaN,NaN,527.2,40.00,NaN,₹,16-Jul-2026
4,SHP-100001,Delivered,Forward,2026-07-12,4590,SEV-000005,1,NaN,N,TRK-9001,...,PREPAID,NaN,NaN,NaN,NaN,527.20 INR,Rs. 40.00,NaN,inr,2026/07/16

In [410]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Payment_Method,Remittance_Amount,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date
495,SHP-100018,In Transit,Forward,11 August 2026,4620,SEV-000496,1,NaN,no,TRK-9016,...,COD,NaN,NaN,NaN,NaN,843.28 INR,NaN,NaN,INR,12 August 2026
496,SHP-100019,In Transit,Forward,2026-09-19,37584,SEV-000497,1,NaN,0,TRK-9017,...,COD,NaN,NaN,NaN,NaN,190.58 INR,25.00,NaN,INR,2026-09-20
497,SHP-100020,In Transit,Forward,04-Jul-2026,11368,SEV-000498,1,NaN,FALSE,TRK-9018,...,Cash on Delivery,NaN,NaN,NaN,NaN,779.32,Rs. 25.00,NaN,INR,2026-07-05
498,SHP-100021,In Transit,Forward,2026-07-27,22950,SEV-000499,1,NaN,N,TRK-9019,...,prepaid,NaN,NaN,NaN,NaN,644.66,₹0.00,NaN,INR,2026/07/28
499,SHP-100022,In Transit,Forward,2026-07-05,32760,SEV-000500,1,NaN,N,TRK-9020,...,PREPAID,NaN,NaN,NaN,NaN,585.53 INR,NaN,NaN,INR,2026-07-06

# 4. Normalize shipment statuses (created, picked up, in transit, out for delivery, delivered, returned, exception).

 Convert shipment statuses to lowercase and remove extra spaces

In [411]:
df['Shipment_Status'] = df['Shipment_Status'].str.strip().str.title()

In [412]:
df['Shipment_Status'] = df['Shipment_Status'].replace({
    'pickup': 'picked up',
    'picked-up': 'picked up',
    'return': 'returned',
    'delivery exception': 'exception'
})

In [413]:
df['Shipment_Status'].unique()

array(['Created', 'Picked Up', 'In Transit', 'Out_For_Delivery',
       'Delivered', 'Out For Delivery', 'Picked_Up', 'In_Transit'],
      dtype=object)

In [414]:
print(df['Shipment_Status'].value_counts())

Shipment_Status
Created             101
Delivered            93
Picked Up            80
In Transit           74
Out For Delivery     71
In_Transit           32
Picked_Up            27
Out_For_Delivery     22
Name: count, dtype: int64

In [415]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Payment_Method,Remittance_Amount,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date
495,SHP-100018,In Transit,Forward,11 August 2026,4620,SEV-000496,1,NaN,no,TRK-9016,...,COD,NaN,NaN,NaN,NaN,843.28 INR,NaN,NaN,INR,12 August 2026
496,SHP-100019,In Transit,Forward,2026-09-19,37584,SEV-000497,1,NaN,0,TRK-9017,...,COD,NaN,NaN,NaN,NaN,190.58 INR,25.00,NaN,INR,2026-09-20
497,SHP-100020,In Transit,Forward,04-Jul-2026,11368,SEV-000498,1,NaN,FALSE,TRK-9018,...,Cash on Delivery,NaN,NaN,NaN,NaN,779.32,Rs. 25.00,NaN,INR,2026-07-05
498,SHP-100021,In Transit,Forward,2026-07-27,22950,SEV-000499,1,NaN,N,TRK-9019,...,prepaid,NaN,NaN,NaN,NaN,644.66,₹0.00,NaN,INR,2026/07/28
499,SHP-100022,In Transit,Forward,2026-07-05,32760,SEV-000500,1,NaN,N,TRK-9020,...,PREPAID,NaN,NaN,NaN,NaN,585.53 INR,NaN,NaN,INR,2026-07-06

# 5. Deduplicate repeated scan events using tracking ID, event code, timestamp, location, and source priority.

In [416]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Shipment_ID', 'Shipment_Status', 'Shipment_Type', 'Shipment_Date', 'Shipment_Volume', 'Shipment_Event_ID', 'Ordinal_Shipment_ID', 'Return_Shipment_ID', 'Return_To_Sender_Flag', 'Tracking_ID', 'Parcel_ID', 'Parcel_Count', 'Parcel_Weight', 'Parcel_Volume', 'Parcel_Status', 'Package_Weight', 'Weight', 'Weight_Unit', 'Length', 'Width', 'Height', 'Dimension_Unit', 'Declared_Value', 'Carrier_ID', 'Carrier_Name', 'Carrier_Alias', 'Service_Type', 'Service_Level', 'Booking_Date', 'Booking_Weekday', 'Pickup_Timestamp', 'Actual_Delivery_Timestamp', 'Delivery_Timestamp', 'Promised_Delivery_Date', 'Promised_Delivery_Timestamp', 'Promised_Pickup_Timestamp', 'Promised_Delivery_Start', 'Promised_Delivery_End', 'Delivery_Attempt_Count', 'Delivery_Attempt_ID', 'Delivery_Attempt_Number', 'First_Attempt_Timestamp', 'First_Attempt_Delivery_Flag', 'First_Attempt_Status', 'Attempt_Number', 'Attempt_Status', 'Attempt_Timestamp', 'Delivery_Success_Flag', 'On_Time_Delivery_Flag', 'Delivery_Location', 'Delivery_Quantity', 'Order_Quantity', 'Delivery_Zone', 'Delay_Minutes', 'Transit_Time_Hours', 'Planned_Transit_Time_Hours', 'Actual_Transit_Time_Hours', 'Route_ID', 'Planned_Route_ID', 'Route_Sequence', 'Stop_ID', 'Stop_Sequence', 'Planned_Stop_Sequence', 'Actual_Stop_Sequence', 'Planned_Stop_Count', 'Completed_Stop_Count', 'Stop_Status', 'Skipped_Stop_Flag', 'Duplicate_Stop_Flag', 'Depot_ID', 'Depot_Name', 'Warehouse_Name', 'Warehouse_Arrival_Timestamp', 'Warehouse_Departure_Timestamp', 'Origin', 'Destination_Zone', 'Customer_Name', 'Customer_Phone', 'Street_Address', 'Address_Line_1', 'Address_Line_2', 'City', 'State', 'Country_Code', 'Postal_Code', 'Location_ID', 'Location_Name', 'Location_Mapping_Status', 'Latitude', 'Longitude', 'Previous_Latitude', 'Previous_Longitude', 'GPS_Timestamp', 'GPS_Speed', 'GPS_Distance', 'GPS_Jump_Distance', 'GPS_Jump_Flag', 'Missing_Coordinate_Flag', 'Event_ID', 'Event_Type', 'Event_Code', 'Event_Date', 'Event_Time', 'Event_Timestamp', 'Event_Timestamp_UTC', 'Timezone_Offset', 'UTC_Offset_Minutes', 'Time_Window', 'Source_Timezone', 'Source_Priority', 'Scan_Timestamp', 'Scan_Sequence', 'Event_Order_Flag', 'Expected_Scan_Count', 'Actual_Scan_Count', 'Missing_Event_Flag', 'Scan_Compliance_Status', 'Exception_Code', 'Exception_Type', 'Exception_Reason', 'Exception_Flag', 'Exception_Timestamp', 'Failure_Code', 'Failure_Reason', 'Exclusion_Reason', 'Damage_Flag', 'Loss_Flag', 'Holiday_Flag', 'Status_Code', 'Status_Description', 'Status_Timestamp', 'POD_Status', 'POD_Timestamp', 'Proof_Of_Delivery_ID', 'Recipient_Name', 'Signature_Confirmation', 'Label_Status', 'Consignment_Status', 'COD_Flag', 'COD_Amount', 'COD_Collected_Amount', 'COD_Collected_Status', 'COD_Collected_Timestamp', 'Outstanding_COD_Amount', 'Payment_Method', 'Remittance_Amount', 'Remittance_Timestamp', 'Reconciliation_Status', 'Reconciliation_Date', 'Freight_Charge', 'Surcharge_Amount', 'Claim_Amount', 'Currency_Code', 'Reporting_Date']

basically in our data we dont have the column name location so we use (Depot_name) insted of location

In [417]:
df = df.drop_duplicates(
    subset=['Tracking_ID', 'Event_Code', 'Event_Timestamp','Depot_Name'],
    keep='first'
)

In [418]:
df['Depot_Name'].unique()

array([nan, 'BHUBANESWAR DEPOT', 'CUTTACK DEPOT', 'BERHAMPUR DEPOT',
       'SAMBALPUR DEPOT', 'PURI DEPOT', 'ROURKELA DEPOT'], dtype=object)

In [419]:
print(df.columns.tolist())

['Shipment_ID', 'Shipment_Status', 'Shipment_Type', 'Shipment_Date', 'Shipment_Volume', 'Shipment_Event_ID', 'Ordinal_Shipment_ID', 'Return_Shipment_ID', 'Return_To_Sender_Flag', 'Tracking_ID', 'Parcel_ID', 'Parcel_Count', 'Parcel_Weight', 'Parcel_Volume', 'Parcel_Status', 'Package_Weight', 'Weight', 'Weight_Unit', 'Length', 'Width', 'Height', 'Dimension_Unit', 'Declared_Value', 'Carrier_ID', 'Carrier_Name', 'Carrier_Alias', 'Service_Type', 'Service_Level', 'Booking_Date', 'Booking_Weekday', 'Pickup_Timestamp', 'Actual_Delivery_Timestamp', 'Delivery_Timestamp', 'Promised_Delivery_Date', 'Promised_Delivery_Timestamp', 'Promised_Pickup_Timestamp', 'Promised_Delivery_Start', 'Promised_Delivery_End', 'Delivery_Attempt_Count', 'Delivery_Attempt_ID', 'Delivery_Attempt_Number', 'First_Attempt_Timestamp', 'First_Attempt_Delivery_Flag', 'First_Attempt_Status', 'Attempt_Number', 'Attempt_Status', 'Attempt_Timestamp', 'Delivery_Success_Flag', 'On_Time_Delivery_Flag', 'Delivery_Location', 'Delivery_Quantity', 'Order_Quantity', 'Delivery_Zone', 'Delay_Minutes', 'Transit_Time_Hours', 'Planned_Transit_Time_Hours', 'Actual_Transit_Time_Hours', 'Route_ID', 'Planned_Route_ID', 'Route_Sequence', 'Stop_ID', 'Stop_Sequence', 'Planned_Stop_Sequence', 'Actual_Stop_Sequence', 'Planned_Stop_Count', 'Completed_Stop_Count', 'Stop_Status', 'Skipped_Stop_Flag', 'Duplicate_Stop_Flag', 'Depot_ID', 'Depot_Name', 'Warehouse_Name', 'Warehouse_Arrival_Timestamp', 'Warehouse_Departure_Timestamp', 'Origin', 'Destination_Zone', 'Customer_Name', 'Customer_Phone', 'Street_Address', 'Address_Line_1', 'Address_Line_2', 'City', 'State', 'Country_Code', 'Postal_Code', 'Location_ID', 'Location_Name', 'Location_Mapping_Status', 'Latitude', 'Longitude', 'Previous_Latitude', 'Previous_Longitude', 'GPS_Timestamp', 'GPS_Speed', 'GPS_Distance', 'GPS_Jump_Distance', 'GPS_Jump_Flag', 'Missing_Coordinate_Flag', 'Event_ID', 'Event_Type', 'Event_Code', 'Event_Date', 'Event_Time', 'Event_Timestamp', 'Event_Timestamp_UTC', 'Timezone_Offset', 'UTC_Offset_Minutes', 'Time_Window', 'Source_Timezone', 'Source_Priority', 'Scan_Timestamp', 'Scan_Sequence', 'Event_Order_Flag', 'Expected_Scan_Count', 'Actual_Scan_Count', 'Missing_Event_Flag', 'Scan_Compliance_Status', 'Exception_Code', 'Exception_Type', 'Exception_Reason', 'Exception_Flag', 'Exception_Timestamp', 'Failure_Code', 'Failure_Reason', 'Exclusion_Reason', 'Damage_Flag', 'Loss_Flag', 'Holiday_Flag', 'Status_Code', 'Status_Description', 'Status_Timestamp', 'POD_Status', 'POD_Timestamp', 'Proof_Of_Delivery_ID', 'Recipient_Name', 'Signature_Confirmation', 'Label_Status', 'Consignment_Status', 'COD_Flag', 'COD_Amount', 'COD_Collected_Amount', 'COD_Collected_Status', 'COD_Collected_Timestamp', 'Outstanding_COD_Amount', 'Payment_Method', 'Remittance_Amount', 'Remittance_Timestamp', 'Reconciliation_Status', 'Reconciliation_Date', 'Freight_Charge', 'Surcharge_Amount', 'Claim_Amount', 'Currency_Code', 'Reporting_Date']

# 6. Normalize weight and dimension units (g/kg, cm/m, lb/in) with explicit conversion rules.

Convert weight to kilograms

In [420]:
df['Weight_kg'] = df['Weight'] * 1.0

df.loc[df['Weight_Unit'] == 'g', 'Weight_kg'] = df['Weight'] / 1000
df.loc[df['Weight_Unit'] == 'lb', 'Weight_kg'] = df['Weight'] * 0.453592

Convert length to centimeters

In [421]:
df['Length'] = df['Length'].replace('?', pd.NA)

In [422]:
df['Length'] = pd.to_numeric(df['Length'], errors='coerce')

In [423]:
df['Length_cm'] = df['Length']

df.loc[df['Dimension_Unit'] == 'm', 'Length_cm'] = df['Length'] * 100

df.loc[df['Dimension_Unit'] == 'in', 'Length_cm'] = df['Length'] * 2.54

In [424]:
df['Dimension_Unit'].unique()

array(['"', 'IN', 'inch', 'inches', 'in', 'Cm', 'centimeter', 'CM', 'cm',
       'M', 'm', 'meter', 'mtr'], dtype=object)

In [425]:
print(df['Length'].head(10))
print(df['Length'].dtype)

0      NaN
1    11.81
2    11.81
3    11.81
4    11.81
5    11.81
6    20.47
7    20.47
8    20.47
9    20.47
Name: Length, dtype: float64
float64

# 7. Validate package weight, dimensions, declared value, and parcel count against allowable ranges.

Check invalid weight

In [426]:
df.loc[df['Weight'] <= 0, 'Weight'] = None

Check invalid dimensions

In [427]:
df['Length'] = pd.to_numeric(df['Length'], errors='coerce')
df['Width'] = pd.to_numeric(df['Width'], errors='coerce')
df['Height'] = pd.to_numeric(df['Height'], errors='coerce')

df.loc[df['Length'] <= 0, 'Length'] = None
df.loc[df['Width'] <= 0, 'Width'] = None
df.loc[df['Height'] <= 0, 'Height'] = None

 Check invalid declared value

In [428]:
df['Declared_Value'] = pd.to_numeric(df['Declared_Value'], errors='coerce')
df.loc[df['Declared_Value'] < 0, 'Declared_Value'] = None

Check invalid parcel count

In [429]:
df['Parcel_Count'] = pd.to_numeric(df['Parcel_Count'], errors='coerce')
df.loc[df['Parcel_Count'] <= 0, 'Parcel_Count'] = None

In [430]:
df['Declared_Value'].unique()

array([   nan, 11387.,  6843.,  4862.,   452.,  5411.,  3239., 12334.,
        5746.,  3563., 10386.,  5853.,  5042.,  8612., 10650.,  3579.,
        5173.,  4220., 14965.,  6798.,  5214.,  6653.,  3025.,  3299.,
       11792.,  2546.,  7728.,  1129.,  1275.,  3412.,  9583.,  4708.,
        8980.,  5233.,  8214., 12043.,  6649.,  1939.,  6471.,  1900.,
        6942.,  1187., 14208.,  2975.,  5844., 13971., 12549.,  6186.,
       12887., 12246., 12300.,  8087.,  8583., 10120., 10632.,  3084.,
       12639.,  6409.,  9374., 13686.,  9375.,  9675., 14434., 11485.,
       10566., 10342.,  3426.,   597.,  8242.,  5869., 12179.,  1446.,
        5659.,  5614.,  8012., 13640.,   572., 14265., 10995., 10945.,
        1556.,   395.,  3773.,  5081.])

In [431]:
df.head()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm
0,SHP-100001,Created,FORWARD,2026/07/12,4590,SEV-000001,1,NaN,0,TRK-9001,...,NaN,NaN,NaN,₹527.20,₹40.00,NaN,INR,12 July 2026,1500.0,NaN
1,SHP-100001,Picked Up,Forward,12 July 2026,4590,SEV-000002,1,NaN,No,TRK-9001,...,NaN,NaN,NaN,527.2,40.00,NaN,INR,2026-07-12,1500.0,11.81
2,SHP-100001,In Transit,Forward,2026/07/12,4590,SEV-000003,1,NaN,0,TRK-9001,...,NaN,NaN,NaN,527.2,40.00 INR,NaN,INR,13 July 2026,1500.0,11.81
3,SHP-100001,Out_For_Delivery,Forward,2026-07-12,4590,SEV-000004,1,NaN,FALSE,TRK-9001,...,NaN,NaN,NaN,527.2,40.00,NaN,₹,16-Jul-2026,1500.0,11.81
4,SHP-100001,Delivered,Forward,2026-07-12,4590,SEV-000005,1,NaN,N,TRK-9001,...,NaN,NaN,NaN,527.20 INR,Rs. 40.00,NaN,inr,2026/07/16,1500.0,11.81

# 8. Standardize postal codes, country codes, and depot/location identifiers.

In [432]:

df['Postal_Code'] = df['Postal_Code'].astype('string').str.strip().str.upper().str.replace(' ', '').str.replace('-', '')

df['Country_Code'] = df['Country_Code'].astype('string').str.strip().str.upper().replace({
    'INDIAD': 'IND',
    'INDIADIA': 'IND',
    'INDIA': 'IND'
})

df['Depot_ID'] = df['Depot_ID'].astype('string').str.strip().str.upper()

df['Location_ID'] = df['Location_ID'].astype('string').str.strip().str.upper()

In [433]:
df['Country_Code'].unique()

<StringArray>
['IND', 'IN']
Length: 2, dtype: string

In [434]:
df['Location_ID'].unique()

<StringArray>
['LOC-NORTH', 'LOC-HUB01',  'LOC-BBSR', 'LOC-SOUTH',   'LOC-CTC',   'LOC-BER',
  'LOC-EAST',  'LOC-WEST',   'LOC-SBP',  'LOC-PURI',   'LOC-RKL']
Length: 11, dtype: string

In [435]:
df['Postal_Code'].unique()

<StringArray>
['751001', '753001', '760001', '768001', '752001', '769001']
Length: 6, dtype: string

In [436]:
df.head()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm
0,SHP-100001,Created,FORWARD,2026/07/12,4590,SEV-000001,1,NaN,0,TRK-9001,...,NaN,NaN,NaN,₹527.20,₹40.00,NaN,INR,12 July 2026,1500.0,NaN
1,SHP-100001,Picked Up,Forward,12 July 2026,4590,SEV-000002,1,NaN,No,TRK-9001,...,NaN,NaN,NaN,527.2,40.00,NaN,INR,2026-07-12,1500.0,11.81
2,SHP-100001,In Transit,Forward,2026/07/12,4590,SEV-000003,1,NaN,0,TRK-9001,...,NaN,NaN,NaN,527.2,40.00 INR,NaN,INR,13 July 2026,1500.0,11.81
3,SHP-100001,Out_For_Delivery,Forward,2026-07-12,4590,SEV-000004,1,NaN,FALSE,TRK-9001,...,NaN,NaN,NaN,527.2,40.00,NaN,₹,16-Jul-2026,1500.0,11.81
4,SHP-100001,Delivered,Forward,2026-07-12,4590,SEV-000005,1,NaN,N,TRK-9001,...,NaN,NaN,NaN,527.20 INR,Rs. 40.00,NaN,inr,2026/07/16,1500.0,11.81

In [437]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Remittance_Timestamp,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm
490,SHP-100007,Picked Up,Forward,2026-07-18,21168,SEV-000491,1,NaN,n,TRK-9007,...,NaN,NaN,NaN,399.37,₹40.00,NaN,inr,"Jul 18, 2026",-1.81,19.29
491,SHP-100008,Picked Up,Forward,2026/07/28,10166,SEV-000492,1,NaN,N,TRK-9008,...,NaN,NaN,NaN,824.58,₹25.00,NaN,Rs,2026-07-28,17.36,34.00
492,SHP-100009,Picked_Up,Forward,2026-08-10,6156,SEV-000493,1,NaN,FALSE,TRK-9009,...,NaN,NaN,NaN,Rs. 660.58,0.00,NaN,INR,"Aug 10, 2026",5.19,27.00
493,SHP-100010,Picked_Up,Forward,06-Aug-2026,3480,SEV-000494,1,NaN,No,TRK-9010,...,NaN,NaN,NaN,Rs. 285.30,NaN,NaN,inr,2026-08-06,16.99,0.20
494,SHP-100011,Picked Up,Forward,2026/09/03,23220,SEV-000495,1,NaN,N,TRK-9011,...,NaN,NaN,NaN,525.61,Rs. 25.00,NaN,Rs,"Sep 03, 2026",10.56,43.00

# 9. Validate GPS latitude/longitude bounds and flag implausible jumps or missing coordinates.

Check invalid latitude and longitude

In [438]:
 
df.loc[(df['Latitude'] < -90) | (df['Latitude'] > 90), 'Latitude'] = None

df.loc[(df['Longitude'] < -180) | (df['Longitude'] > 180), 'Longitude'] = None

 Check GPS jumps between consecutive rows

In [439]:
df['GPS_Jump'] = False

df.loc[df['Latitude'].diff().abs() > 1, 'GPS_Jump'] = True
df.loc[df['Longitude'].diff().abs() > 1, 'GPS_Jump'] = True

Check missing coordinates

In [440]:
df[df['Latitude'].isna() | df['Longitude'].isna()]

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Reconciliation_Status,Reconciliation_Date,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump
32,SHP-100008,In_Transit,Forward,2026/07/28,10166,SEV-000033,1,NaN,0,TRK-9008,...,NaN,NaN,Rs. 824.58,INR 25,NaN,INR,"Jul 29, 2026",17.360000,34.0,False
37,SHP-100009,In_Transit,Forward,10-Aug-2026,6156,SEV-000038,1,NaN,FALSE,TRK-9009,...,NaN,NaN,660.58,0,NaN,INR,2026-08-11,5190.000000,27.0,False
42,SHP-100010,In Transit,Forward,2026-08-06,3480,SEV-000043,1,NaN,FALSE,TRK-9010,...,NaN,NaN,285.30,0,NaN,INR,"Aug 07, 2026",16.991556,0.2,False
47,SHP-100011,In_Transit,Forward,2026/09/03,23220,SEV-000048,1,NaN,n,TRK-9011,...,NaN,NaN,525.61,₹25.00,NaN,INR,2026/09/04,23.280000,43.0,True

In [441]:
df['Latitude'].unique()

array([20.95566, 20.95089, 20.66055, 20.3015 , 20.29215, 19.50361,
       19.50944, 19.98011, 20.47292, 20.4717 , 19.49497, 19.49101,
       19.39654, 19.32492, 19.30441, 20.40864, 20.40011, 20.42543,
       20.45483, 20.46733, 19.49357, 19.50799, 20.00323, 20.40437,
       20.39498, 19.88408, 21.10448, 21.09758, 20.80937, 20.3984 ,
       20.3993 ,      nan, 21.46911, 21.46583, 19.49131, 19.50213,
       20.3    , 21.45855, 21.45149, 21.09696, 21.09176, 20.27983,
       20.31531, 20.40931, 20.39939, 20.28275, 20.2829 , 19.50256,
       19.49264, 19.65358, 19.80824, 19.81941, 19.49667, 19.50801,
       19.84963, 20.31392, 20.29571, 20.39707, 20.397  , 21.37235,
       22.25855, 22.25983, 20.94749, 20.94962, 20.59753, 20.39901,
       20.39728, 20.09009, 20.39729, 20.39736, 20.3535 , 19.49095,
       19.49858, 19.6458 , 20.39546, 20.40454, 19.85189, 19.33311,
       19.32216, 21.1097 , 21.09619, 21.70698, 22.27424, 22.24725,
       20.95069, 20.94489, 20.13284, 19.29681, 19.30015, 20.40443,
       20.39303, 20.97912, 21.47775, 21.47396, 21.09642, 21.10672,
       21.32238, 21.46038, 21.45252, 20.40051, 20.40434, 20.92304,
       21.44817, 21.47304, 21.0928 , 21.0955 , 21.30308, 21.46341,
       21.47588, 19.50728, 19.50101, 19.90044, 20.29633, 20.29753,
       20.39542, 20.40858, 20.06212, 19.81077, 19.80908, 20.95612,
       20.9505 , 20.60304, 20.30337, 20.28167, 20.94402, 20.94304,
       20.13933, 19.31869, 19.29956, 20.40239, 20.39977, 20.94072,
       21.45881, 21.45354, 20.39655, 20.40936, 20.11937, 19.82848,
       19.81067, 21.09246, 21.10558, 20.65932, 20.30661, 20.29304,
       20.9484 , 20.94485, 21.64807, 22.26326, 22.24386, 20.9432 ,
       20.94714, 20.68793, 20.45835, 20.44736, 20.94292, 20.95129,
       20.65477, 20.30666, 20.30424, 21.10937, 21.10702, 20.66484,
       20.27803, 20.28261, 21.09399, 21.0937 , 20.41532, 19.81641,
       19.80198, 21.09078, 21.10686, 20.23159, 19.30195, 19.32042,
       20.95339, 20.95893, 21.22738, 21.47596, 21.45202, 20.40153,
       20.40068, 19.85783, 19.30871, 19.31519, 20.94886, 20.95318,
       20.65522, 20.28164, 20.30953, 21.09297, 21.09983, 20.20735,
       19.3306 , 19.32364, 19.50461, 19.50941, 20.89262, 22.26371,
       22.26721, 20.96137, 20.94181, 21.60859, 22.24914, 22.27876,
       20.40822, 20.40402, 20.31368, 20.3144 , 20.28457, 20.95636,
       20.94696, 21.22469, 21.45646, 21.47634, 20.94215, 21.6439 ,
       22.26533, 22.27346, 21.09818, 21.10104, 20.20216, 19.33203,
       19.33283, 20.95176, 20.96092, 21.20054, 21.46596, 21.45501,
       20.39374, 20.39559, 20.13732, 19.80212, 19.80997, 20.39469,
       20.40542, 19.82063, 19.31863, 19.30539, 20.39376, 20.39029,
       21.29836, 22.25883, 22.25053, 20.94671, 20.94308, 20.7347 ,
       20.46814, 20.46882, 20.95936, 20.9586 , 21.20405, 21.48366,
       21.45715, 21.10573, 21.0927 , 20.71522, 20.29372, 20.3094 ,
       21.09373, 21.10369, 20.19168, 19.31297, 19.32125, 20.40485,
       20.40216, 21.33597, 22.25218, 22.25612, 20.95165, 20.94659,
       20.60701, 20.30607, 20.30388, 20.39023, 20.40664, 20.96185,
       21.44955, 21.47511, 20.94376, 20.94715, 20.34973, 19.81056,
       19.83245, 19.50096, 19.50339, 19.94212, 20.47278, 20.47924,
       20.94201, 20.95416, 20.12443, 19.3136 , 19.30874, 20.3997 ,
       20.39422, 20.92143, 21.48361, 21.47627, 19.49515, 19.50959,
       19.61024, 19.82968, 19.83167, 21.09811, 21.10308, 20.73159,
       20.28907, 20.30395, 19.49928, 19.50845, 19.86385, 20.30726,
       20.31322, 19.50828, 19.49991, 19.67708, 19.82792, 19.82501,
       20.9577 , 20.945  , 21.18845, 21.46522, 21.45828, 20.95769,
       20.95062, 20.59335, 20.2899 , 20.30524, 20.94227, 20.94916,
       20.63752, 20.29785, 20.28736, 21.09155, 21.09603, 21.66542,
       22.24727, 22.27379, 20.94299, 20.95683, 20.14619, 19.32541,
       19.3331 , 21.09761, 21.09229, 21.66185, 22.25238, 22.26911,
       20.39534, 20.4012 , 21.37658, 22.25628, 22.27578, 21.1007 ,
       21.10832, 20.49443, 19.82398, 19.81415, 20.95825, 20.95623,
       20.70399, 20.45581, 20.44779, 20.94252, 20.9584 , 20.40943,
       19.79674, 19.80195, 20.94356, 20.95984, 20.6152 , 20.27791,
       20.28454, 21.10928, 21.10695, 21.25664, 21.46483, 21.45215,
       19.50793, 19.50647, 19.99596, 20.45314, 20.47842, 21.10551,
       21.10514, 20.41913, 19.80751, 19.82464, 21.09307, 21.09431,
       20.2337 , 19.30856, 19.32076, 19.50922, 19.49104, 19.6701 ,
       19.79686, 19.82601, 20.40384, 20.40575, 19.81998, 19.32734,
       19.29944, 20.94334, 20.95421, 20.75145, 20.47381, 20.44633,
       20.94787, 20.94858, 21.22091, 21.47628, 21.4526 , 19.50842,
       19.49418, 19.96343, 20.45128, 20.47256, 20.39017, 20.39454,
       20.10062, 19.82401, 19.83271, 19.5015 , 19.50052, 19.88716,
       20.30405, 20.29255, 21.09337, 21.10673, 21.32433, 21.47586,
       21.45545, 19.49618, 19.50847, 19.92311, 20.29696, 20.29981,
       20.39144, 20.40941, 20.10771, 19.8214 , 19.79719, 20.39269,
       20.40966, 19.85602, 19.33229, 19.33401, 19.49256, 19.50507,
       20.5    , 21.48331, 21.47652, 21.09118, 21.09598, 21.70288,
       22.2587 , 22.26944, 21.09768, 21.09788, 20.21297, 19.30954,
       19.30059, 19.49633, 19.49726, 19.41015, 19.29692, 19.30071,
       21.10428, 21.09734, 20.43576, 19.7958 , 19.81318, 21.0965 ,
       20.4317 , 19.80105, 19.79714, 20.3942 , 20.39603, 20.14624,
       19.80509, 19.82353, 20.39649, 20.40445, 19.83067])

In [442]:
df['Longitude'].unique()

array([85.09531, 85.091  , 85.44951, 85.82587, 85.80715, 84.89229,
       84.90524, 85.35269, 85.89363, 85.87105, 84.8938 , 84.90999,
       84.8897 , 84.77639, 84.7789 , 86.19207, 86.19502, 86.06207,
       85.89896, 85.86918, 84.90925, 85.37153, 86.19768, 86.20697,
       85.49918, 84.05681, 84.04423, 84.98168, 86.1998 , 86.20651,
       85.8    , 83.97081, 83.98244, 84.89983, 84.90581,      nan,
       83.97046, 83.97019, 84.04667, 84.04505, 85.84419, 85.81425,
       86.19664, 86.20938, 85.1    , 85.81648, 85.80766, 84.90807,
       84.90079, 85.32313, 85.84116, 85.83662, 84.90978, 84.89006,
       85.33879, 85.80623, 85.84089, 86.20331, 86.20113, 85.5119 ,
       84.8399 , 84.85128, 85.0966 , 85.09471, 85.42614, 86.20622,
       86.20836, 86.02387, 86.20439, 86.20894, 85.97251, 84.8984 ,
       84.9023 , 85.36261, 86.20599, 86.19158, 85.49176, 84.77981,
       84.81205, 84.05584, 84.05999, 84.4147 , 84.84362, 84.85858,
       85.09132, 85.10842, 84.98453, 84.77615, 84.77797, 86.20167,
       86.20381, 85.08657, 83.9894 , 83.97639, 84.05292, 84.05576,
       83.97902, 83.973  , 83.97414, 86.20056, 86.19978, 85.12225,
       83.97755, 83.97511, 84.05987, 84.05113, 84.00643, 83.97786,
       83.96882, 84.90483, 84.90887, 85.39616, 85.81943, 85.81597,
       86.20848, 86.19599, 86.00931, 85.83839, 85.82563, 85.09842,
       85.09711, 85.481  , 85.8265 , 85.81661, 85.10731, 85.08939,
       84.99215, 84.78965, 84.80093, 86.20731, 86.19165, 85.06739,
       84.00117, 83.96677, 86.19005, 86.2065 , 86.04927, 85.84626,
       85.81485, 84.0546 , 84.05381, 84.93721, 85.84268, 85.82059,
       85.09709, 85.10397, 84.94395, 84.83838, 84.85187, 85.09986,
       85.08999, 85.46725, 85.86496, 85.86547, 85.0941 , 85.10413,
       85.45867, 85.84241, 85.81857, 84.05387, 84.05542, 84.97578,
       85.82203, 85.80745, 84.04051, 84.05771, 84.92498, 85.82063,
       85.81891, 84.05779, 84.05716, 84.448  , 84.80911, 84.77905,
       85.08865, 85.09372, 84.56198, 83.97009, 83.97155, 86.19317,
       86.20461, 85.47766, 84.81016, 84.77903, 85.0967 , 85.09838,
       85.49891, 85.83039, 85.8321 , 84.05653, 84.04482, 84.40366,
       84.79659, 84.77866, 84.89257, 84.89906, 84.85586, 84.87131,
       84.8416 , 85.09783, 85.02175, 84.86371, 84.8609 , 86.19815,
       86.19145, 85.98424, 85.80495, 85.84073, 85.10606, 85.10623,
       84.50471, 83.99976, 83.98054, 85.10054, 85.08936, 84.99885,
       84.85403, 84.85782, 84.04213, 84.05115, 84.44198, 84.79152,
       84.80691, 85.0953 , 85.09768, 84.52516, 83.97534, 83.97119,
       86.19526, 86.1936 , 85.98326, 85.82137, 85.82524, 86.19503,
       86.20048, 85.5309 , 84.79236, 84.78624, 86.19039, 86.19434,
       85.56637, 84.86444, 84.85914, 85.08929, 85.0916 , 85.46463,
       85.86742, 85.88403, 85.09184, 85.09675, 84.52956, 83.98165,
       83.97321, 84.04296, 84.05119, 84.9296 , 85.84147, 85.81601,
       84.05001, 84.04711, 84.41133, 84.77937, 84.79669, 86.20976,
       86.20649, 85.52841, 84.87036, 84.84654, 85.09847, 85.09945,
       85.42027, 85.81548, 86.19402, 86.19388, 85.082  , 83.96717,
       83.97378, 85.10382, 85.09165, 85.44599, 85.81836, 85.84143,
       84.90948, 84.90479, 85.42291, 85.88944, 85.90047, 85.10293,
       85.09759, 84.95092, 84.77723, 84.80524, 86.20469, 85.11116,
       83.9867 , 83.98475, 84.90561, 84.89401, 85.32264, 85.83419,
       85.84392, 84.04942, 84.89365, 85.84353, 85.82664, 84.90253,
       84.89108, 85.31516, 85.81755, 85.8227 , 84.90797, 84.89166,
       85.40139, 85.81403, 85.81444, 85.10741, 85.09074, 84.49614,
       83.98389, 83.99945, 85.10307, 85.09035, 85.44328, 85.81682,
       85.82107, 85.10379, 85.10316, 85.50702, 85.8394 , 85.83565,
       84.05549, 84.04021, 84.48731, 84.86376, 84.87285, 85.108  ,
       85.10452, 84.90976, 84.80054, 84.77536, 84.04856, 84.0434 ,
       84.45884, 84.87238, 84.85673, 86.19574, 86.19872, 85.52538,
       84.86719, 84.84312, 84.04473, 84.05263, 84.97262, 85.83685,
       85.84999, 85.09229, 85.52789, 85.87239, 85.89869, 85.09563,
       85.1035 , 85.48254, 85.84443, 85.81315, 85.09877, 85.09805,
       85.45797, 85.82115, 85.80763, 84.04943, 84.04864, 83.97167,
       83.97865, 83.97294, 84.90707, 84.89084, 85.37496, 85.89161,
       85.90107, 84.05762, 84.0432 , 84.96626, 85.82258, 85.82937,
       84.04743, 84.05638, 84.42253, 84.77593, 84.77751, 84.89363,
       84.89479, 85.40697, 85.83663, 85.84964, 86.20293, 86.20298,
       85.4841 , 84.78295, 84.78519, 85.09994, 85.08906, 85.51832,
       85.86548, 85.89308, 85.09536, 85.10803, 84.53172, 83.9993 ,
       83.97882, 84.90526, 84.89163, 85.37889, 85.87112, 85.8748 ,
       86.20498, 86.05089, 85.83882, 85.81937, 84.89621, 84.90821,
       85.39459, 85.80625, 85.83497, 84.05343, 84.05623, 83.9856 ,
       83.96296, 83.97546, 84.90476, 84.90196, 85.33515, 85.81184,
       85.83775, 86.19273, 86.19746, 86.01446, 85.83701, 85.83966,
       86.19973, 86.20743, 85.5231 , 84.79303, 84.80902, 84.90594,
       84.90319, 84.48287, 83.99092, 83.99869, 84.0562 , 84.0563 ,
       84.43004, 84.84015, 84.85663, 84.06   , 84.05635, 84.4521 ,
       84.79588, 84.79372, 84.90576, 84.89667, 84.8846 , 84.78682,
       84.7968 , 84.05405, 84.04267, 84.93891, 85.81144, 85.81459,
       84.05529, 84.04104, 84.96727, 85.84539, 85.81324, 86.19948,
       86.01045, 85.84943, 85.82657, 86.19115, 86.20376, 85.51968])

# 10. Normalize route and stop sequence numbers; detect duplicate or skipped stops.

Convert stop sequence to numbers

In [443]:
df['Stop_Sequence'] = pd.to_numeric(df['Stop_Sequence'], errors='coerce')

 duplicate stops

In [444]:
df['Duplicate_Stop'] = df.duplicated(
    subset=['Route_ID', 'Stop_Sequence']
)

skipped stops

In [445]:
df = df.sort_values(['Route_ID', 'Stop_Sequence'])

df['Skipped_Stop'] = df.groupby('Route_ID')['Stop_Sequence'].diff() > 1

In [446]:
df[['Route_ID', 'Stop_Sequence', 'Duplicate_Stop', 'Skipped_Stop']].head()

         Route_ID  Stop_Sequence  Duplicate_Stop  Skipped_Stop
315  RT-BBSR-0714            4.0           False         False
316  RT-BBSR-0714            4.0            True         False
430  RT-BBSR-0715           14.0           False         False
431  RT-BBSR-0715           14.0            True         False
260  RT-BBSR-0715           15.0           False         False

# 11. Link proof-of-delivery events to the correct shipment and delivery attempt.

In [447]:
df.columns[df.columns.str.contains('POD|Attempt|Shipment', case=False)]

Index(['Shipment_ID', 'Shipment_Status', 'Shipment_Type', 'Shipment_Date',
       'Shipment_Volume', 'Shipment_Event_ID', 'Ordinal_Shipment_ID',
       'Return_Shipment_ID', 'Delivery_Attempt_Count', 'Delivery_Attempt_ID',
       'Delivery_Attempt_Number', 'First_Attempt_Timestamp',
       'First_Attempt_Delivery_Flag', 'First_Attempt_Status', 'Attempt_Number',
       'Attempt_Status', 'Attempt_Timestamp', 'POD_Status', 'POD_Timestamp'],
      dtype='object')

link and display POD details with each shipment and delivery attempt

In [448]:
df = df.sort_values(['Shipment_ID', 'Delivery_Attempt_ID'])

df[['Shipment_ID',
          'Delivery_Attempt_ID',
          'POD_Status',
          'POD_Timestamp']].head()

  Shipment_ID Delivery_Attempt_ID POD_Status              POD_Timestamp
4  SHP-100001        ATT-100001-1  CAPTURED   2026-07-16T16:14:00+05:30
3  SHP-100001       ATT-100001-1         NaN                        NaN
0  SHP-100001                 NaN        NaN                        NaN
1  SHP-100001                 NaN        NaN                        NaN
2  SHP-100001                 NaN        NaN                        NaN

In [449]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop
483,SHP-100100,Picked Up,forward,15-Jul-2026,4290,SEV-000484,1,NaN,0,TRK-9098,...,309.73 INR,₹40.00,NaN,Rs,15 July 2026,16.14,15.0,False,True,False
484,SHP-100100,In Transit,Forward,"Jul 15, 2026",4290,SEV-000485,1,NaN,n,TRK-9098,...,Rs. 309.73,Rs. 40.00,NaN,INR,16-Jul-2026,16.14,15.0,False,True,False
487,SHP-100101,Created,Forward,2026/09/04,7018,SEV-000488,1,NaN,FALSE,TRK-9099,...,INR 201,INR 15,NaN,Rs,"Sep 04, 2026",5.05,29.0,False,True,False
488,SHP-100101,Picked Up,Forward,2026/09/04,7018,SEV-000489,1,NaN,no,TRK-9099,...,201.47,15,NaN,inr,"Sep 04, 2026",5.05,29.0,False,True,False
489,SHP-100101,In Transit,Forward,2026-09-04,7018,SEV-000490,1,NaN,FALSE,TRK-9099,...,201.47 INR,15.00,NaN,INR,"Sep 05, 2026",5.05,29.0,False,True,False

# 12. Normalize exception and failure reason codes (recipient unavailable, address issue, damaged, weather).

Clean exception and failure reason codes

In [450]:

df['Exception_Reason'] = df['Exception_Reason'].str.strip().str.lower()

In [451]:
df['Exception_Reason'] = df['Exception_Reason'].replace({
    'recipient not available': 'recipient unavailable',
    'address problem': 'address issue',
    'parcel damaged': 'damaged',
    'bad weather': 'weather'
})

In [452]:
df['Exception_Reason'].value_counts()

Exception_Reason
heavy rain delay         4
recipient unavailable    1
address incomplete       1
Name: count, dtype: int64

In [453]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop
483,SHP-100100,Picked Up,forward,15-Jul-2026,4290,SEV-000484,1,NaN,0,TRK-9098,...,309.73 INR,₹40.00,NaN,Rs,15 July 2026,16.14,15.0,False,True,False
484,SHP-100100,In Transit,Forward,"Jul 15, 2026",4290,SEV-000485,1,NaN,n,TRK-9098,...,Rs. 309.73,Rs. 40.00,NaN,INR,16-Jul-2026,16.14,15.0,False,True,False
487,SHP-100101,Created,Forward,2026/09/04,7018,SEV-000488,1,NaN,FALSE,TRK-9099,...,INR 201,INR 15,NaN,Rs,"Sep 04, 2026",5.05,29.0,False,True,False
488,SHP-100101,Picked Up,Forward,2026/09/04,7018,SEV-000489,1,NaN,no,TRK-9099,...,201.47,15,NaN,inr,"Sep 04, 2026",5.05,29.0,False,True,False
489,SHP-100101,In Transit,Forward,2026-09-04,7018,SEV-000490,1,NaN,FALSE,TRK-9099,...,201.47 INR,15.00,NaN,INR,"Sep 05, 2026",5.05,29.0,False,True,False

# 13. Standardize delivery promise dates and distinguish promised date from actual delivery timestamp.

 Convert dates into datetime format

In [454]:

df['Promised_Delivery_Date'] = pd.to_datetime(
    df['Promised_Delivery_Date'], errors='coerce'
)

df['Actual_Delivery_Timestamp'] = pd.to_datetime(
    df['Actual_Delivery_Timestamp'], errors='coerce', utc=True
)

In [455]:
df[['Promised_Delivery_Date', 'Actual_Delivery_Timestamp']].head()

  Promised_Delivery_Date Actual_Delivery_Timestamp
4             2026-07-16 2026-07-16 10:44:00+00:00
3             2026-07-16                       NaT
0             2026-07-16                       NaT
1             2026-07-16                       NaT
2             2026-07-16                       NaT

In [456]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Freight_Charge,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop
483,SHP-100100,Picked Up,forward,15-Jul-2026,4290,SEV-000484,1,NaN,0,TRK-9098,...,309.73 INR,₹40.00,NaN,Rs,15 July 2026,16.14,15.0,False,True,False
484,SHP-100100,In Transit,Forward,"Jul 15, 2026",4290,SEV-000485,1,NaN,n,TRK-9098,...,Rs. 309.73,Rs. 40.00,NaN,INR,16-Jul-2026,16.14,15.0,False,True,False
487,SHP-100101,Created,Forward,2026/09/04,7018,SEV-000488,1,NaN,FALSE,TRK-9099,...,INR 201,INR 15,NaN,Rs,"Sep 04, 2026",5.05,29.0,False,True,False
488,SHP-100101,Picked Up,Forward,2026/09/04,7018,SEV-000489,1,NaN,no,TRK-9099,...,201.47,15,NaN,inr,"Sep 04, 2026",5.05,29.0,False,True,False
489,SHP-100101,In Transit,Forward,2026-09-04,7018,SEV-000490,1,NaN,FALSE,TRK-9099,...,201.47 INR,15.00,NaN,INR,"Sep 05, 2026",5.05,29.0,False,True,False

# 14. Handle missing pickup or delivery events as unknown rather than assuming they occurred.

In [457]:
df['Attempt_Status'] = df['Attempt_Status'].fillna('Unknown')
df['POD_Status'] = df['POD_Status'].fillna('Unknown')

df[['Attempt_Status', 'POD_Status']].head()

  Attempt_Status POD_Status
4        SUCCESS  CAPTURED
3    in_progress    Unknown
0        Unknown    Unknown
1        Unknown    Unknown
2        Unknown    Unknown

# 15. Flag impossible event orderings, such as delivered before pickup, and out-of-order late-arriving scans.

Convert timestamps into datetime format

In [458]:

df['First_Attempt_Timestamp'] = pd.to_datetime(df['First_Attempt_Timestamp'], errors='coerce', utc=True)
df['POD_Timestamp'] = pd.to_datetime(df['POD_Timestamp'], errors='coerce', utc=True)

 Flag delivery before pickup/attempt

In [459]:
df['Impossible_Order'] = df['POD_Timestamp'] < df['First_Attempt_Timestamp']

df[['Shipment_ID', 'First_Attempt_Timestamp', 'POD_Timestamp', 'Impossible_Order']].head()

,Shipment_ID,First_Attempt_Timestamp,POD_Timestamp,Impossible_Order
4,SHP-100001,NaT,2026-07-16 10:44:00+00:00,False
3,SHP-100001,NaT,NaT,False
0,SHP-100001,NaT,NaT,False
1,SHP-100001,NaT,NaT,False
2,SHP-100001,NaT,NaT,False

In [460]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop,Impossible_Order
483,SHP-100100,Picked Up,forward,15-Jul-2026,4290,SEV-000484,1,NaN,0,TRK-9098,...,₹40.00,NaN,Rs,15 July 2026,16.14,15.0,False,True,False,False
484,SHP-100100,In Transit,Forward,"Jul 15, 2026",4290,SEV-000485,1,NaN,n,TRK-9098,...,Rs. 40.00,NaN,INR,16-Jul-2026,16.14,15.0,False,True,False,False
487,SHP-100101,Created,Forward,2026/09/04,7018,SEV-000488,1,NaN,FALSE,TRK-9099,...,INR 15,NaN,Rs,"Sep 04, 2026",5.05,29.0,False,True,False,False
488,SHP-100101,Picked Up,Forward,2026/09/04,7018,SEV-000489,1,NaN,no,TRK-9099,...,15,NaN,inr,"Sep 04, 2026",5.05,29.0,False,True,False,False
489,SHP-100101,In Transit,Forward,2026-09-04,7018,SEV-000490,1,NaN,FALSE,TRK-9099,...,15.00,NaN,INR,"Sep 05, 2026",5.05,29.0,False,True,False,False

In [461]:
df.head()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Surcharge_Amount,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop,Impossible_Order
4,SHP-100001,Delivered,Forward,2026-07-12,4590,SEV-000005,1,NaN,N,TRK-9001,...,Rs. 40.00,NaN,inr,2026/07/16,1500.0,11.81,False,True,False,False
3,SHP-100001,Out_For_Delivery,Forward,2026-07-12,4590,SEV-000004,1,NaN,FALSE,TRK-9001,...,40.00,NaN,₹,16-Jul-2026,1500.0,11.81,False,False,False,False
0,SHP-100001,Created,FORWARD,2026/07/12,4590,SEV-000001,1,NaN,0,TRK-9001,...,₹40.00,NaN,INR,12 July 2026,1500.0,NaN,False,False,False,False
1,SHP-100001,Picked Up,Forward,12 July 2026,4590,SEV-000002,1,NaN,No,TRK-9001,...,40.00,NaN,INR,2026-07-12,1500.0,11.81,False,True,False,False
2,SHP-100001,In Transit,Forward,2026/07/12,4590,SEV-000003,1,NaN,0,TRK-9001,...,40.00 INR,NaN,INR,13 July 2026,1500.0,11.81,False,True,False,False

# 16. Identify test shipments, cancelled labels, and voided consignments using documented exclusion rules.

In [462]:
df['Exclusion_Reason'] = df['Shipment_Status'].str.lower().map({
    'test': 'Test Shipment',
    'cancelled': 'Cancelled Label',
    'canceled': 'Cancelled Label',
    'voided': 'Voided Consignment'
})

df[['Shipment_ID', 'Shipment_Status', 'Exclusion_Reason']].head()

  Shipment_ID   Shipment_Status Exclusion_Reason
4  SHP-100001         Delivered              NaN
3  SHP-100001  Out_For_Delivery              NaN
0  SHP-100001           Created              NaN
1  SHP-100001         Picked Up              NaN
2  SHP-100001        In Transit              NaN

# 17. Normalize freight charges, surcharges, COD amounts, and claim amounts to numeric values and currencies.

In [463]:
df['Freight_Charge'] = pd.to_numeric(df['Freight_Charge'], errors='coerce')
df['Surcharge_Amount'] = pd.to_numeric(df['Surcharge_Amount'], errors='coerce')
df['COD_Amount'] = pd.to_numeric(df['COD_Amount'], errors='coerce')
df['Claim_Amount'] = pd.to_numeric(df['Claim_Amount'], errors='coerce')

df[['Freight_Charge', 'Surcharge_Amount', 'COD_Amount', 'Claim_Amount']].head()

   Freight_Charge  Surcharge_Amount  COD_Amount  Claim_Amount
4             NaN               NaN         NaN           NaN
3           527.2              40.0         NaN           NaN
0             NaN               NaN         NaN           NaN
1           527.2              40.0         NaN           NaN
2           527.2               NaN         NaN           NaN

# 18. Validate return-to-sender records against original shipment identifiers.

Check return shipments

In [464]:

df['Return_Shipment_ID'] = df['Return_Shipment_ID'].astype('string').str.strip()

df['Invalid_Return'] = (
    (df['Shipment_Status'].str.lower() == 'returned') &
    (df['Return_Shipment_ID'].isna() | (df['Return_Shipment_ID'] == ''))
)


df[['Shipment_ID', 'Shipment_Status', 'Return_Shipment_ID', 'Invalid_Return']].head()

  Shipment_ID   Shipment_Status Return_Shipment_ID  Invalid_Return
4  SHP-100001         Delivered               <NA>           False
3  SHP-100001  Out_For_Delivery               <NA>           False
0  SHP-100001           Created               <NA>           False
1  SHP-100001         Picked Up               <NA>           False
2  SHP-100001        In Transit               <NA>           False

In [465]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop,Impossible_Order,Invalid_Return
483,SHP-100100,Picked Up,forward,15-Jul-2026,4290,SEV-000484,1,<NA>,0,TRK-9098,...,NaN,Rs,15 July 2026,16.14,15.0,False,True,False,False,False
484,SHP-100100,In Transit,Forward,"Jul 15, 2026",4290,SEV-000485,1,<NA>,n,TRK-9098,...,NaN,INR,16-Jul-2026,16.14,15.0,False,True,False,False,False
487,SHP-100101,Created,Forward,2026/09/04,7018,SEV-000488,1,<NA>,FALSE,TRK-9099,...,NaN,Rs,"Sep 04, 2026",5.05,29.0,False,True,False,False,False
488,SHP-100101,Picked Up,Forward,2026/09/04,7018,SEV-000489,1,<NA>,no,TRK-9099,...,NaN,inr,"Sep 04, 2026",5.05,29.0,False,True,False,False,False
489,SHP-100101,In Transit,Forward,2026-09-04,7018,SEV-000490,1,<NA>,FALSE,TRK-9099,...,NaN,INR,"Sep 05, 2026",5.05,29.0,False,True,False,False,False

# 19. Mask customer names, phone numbers, and street-address details in analytics extracts.

In [466]:
df.columns[df.columns.str.contains('name|phone|address', case=False)].tolist()

['Carrier_Name',
 'Depot_Name',
 'Warehouse_Name',
 'Customer_Name',
 'Customer_Phone',
 'Street_Address',
 'Address_Line_1',
 'Address_Line_2',
 'Location_Name',
 'Recipient_Name']

customer names

In [467]:
df['Customer_Name'] = 'Mask'
df['Recipient_Name'] = 'Mask'

phone no

In [468]:
df['Customer_Phone'] = '********'

Address

In [469]:
df['Street_Address'] = 'Masked'
df['Address_Line_1'] = 'Masked'
df['Address_Line_2'] = 'Masked'

In [470]:
df.tail()

,Shipment_ID,Shipment_Status,Shipment_Type,Shipment_Date,Shipment_Volume,Shipment_Event_ID,Ordinal_Shipment_ID,Return_Shipment_ID,Return_To_Sender_Flag,Tracking_ID,...,Claim_Amount,Currency_Code,Reporting_Date,Weight_kg,Length_cm,GPS_Jump,Duplicate_Stop,Skipped_Stop,Impossible_Order,Invalid_Return
483,SHP-100100,Picked Up,forward,15-Jul-2026,4290,SEV-000484,1,<NA>,0,TRK-9098,...,NaN,Rs,15 July 2026,16.14,15.0,False,True,False,False,False
484,SHP-100100,In Transit,Forward,"Jul 15, 2026",4290,SEV-000485,1,<NA>,n,TRK-9098,...,NaN,INR,16-Jul-2026,16.14,15.0,False,True,False,False,False
487,SHP-100101,Created,Forward,2026/09/04,7018,SEV-000488,1,<NA>,FALSE,TRK-9099,...,NaN,Rs,"Sep 04, 2026",5.05,29.0,False,True,False,False,False
488,SHP-100101,Picked Up,Forward,2026/09/04,7018,SEV-000489,1,<NA>,no,TRK-9099,...,NaN,inr,"Sep 04, 2026",5.05,29.0,False,True,False,False,False
489,SHP-100101,In Transit,Forward,2026-09-04,7018,SEV-000490,1,<NA>,FALSE,TRK-9099,...,NaN,INR,"Sep 05, 2026",5.05,29.0,False,True,False,False,False

# 20. Flag duplicate tracking IDs across active shipments and unresolved location mappings.

Flag duplicate tracking IDs

In [471]:
df['Duplicate_Tracking_ID'] = df.duplicated(
    subset=['Tracking_ID'], keep=False
)

Flag missing location mappings

In [472]:
df['Missing_Location'] = df['Location_Name'].isna()

In [473]:
df[['Tracking_ID', 'Shipment_Status', 'Location_Name',
          'Duplicate_Tracking_ID', 'Missing_Location']].head()

,Tracking_ID,Shipment_Status,Location_Name,Duplicate_Tracking_ID,Missing_Location
4,TRK-9001,Delivered,Bhubaneswar Depot,True,False
3,TRK-9001,Out_For_Delivery,Bhubaneswar Depot,True,False
0,TRK-9001,Created,WH-NORTH,True,False
1,TRK-9001,Picked Up,WH-NORTH,True,False
2,TRK-9001,In Transit,Transit Hub,True,False

 Keep the time zone when saving to Excel

In [474]:

for col in df.columns:
    if isinstance(df[col].dtype, pd.DatetimeTZDtype):
        df[col] = df[col].astype(str)


df.to_excel("Logistics_Delivery_Cleaned.xlsx", index=False)

print("File saved with time zones!")

File saved with time zones!